### ISSUE TITLE
Fix hand links mass and inertia inconsistencies

### ISSUE THREAD

**Issue by claudia-lat** [robotology-playground/human-gazebo#12]
Issue https://github.com/robotology/human-gazebo/issues/11#issuecomment-603420750 revealed a bug in [all the models stored in this repo](https://github.com/robotology/human-gazebo).  Models have to be regenerated by following these instructions https://github.com/dic-iit/human-model-generator#how-to-generate-models.

**Comment by yeshasvitirupachuri** [comment]
I generated the new models using the https://github.com/dic-iit/human-model-generator#how-to-generate-models, however I notice that all the fake links mass and inertia values are not zero, as they are in the models currently present in human-gazebo repo. The main difference seems to be in the mass and inertia values of the `RightHand` link, which is different from the `LeftHand`. 


![Screenshot from 2020-04-02 15-14-56](https://user-images.githubusercontent.com/6505998/78253857-57f98000-74f5-11ea-8e7f-2fecce2e3c27.png)


![Screenshot from 2020-04-02 15-15-19](https://user-images.githubusercontent.com/6505998/78253862-5b8d0700-74f5-11ea-99f3-e2fead408f30.png)


So, I think it is best if the `RightHand` link mass and inertia values are set similar to the `LeftHand` link in all the models and we correct them manually rather than regenerating all the models again. 

@claudia-lat @lrapetti @DanielePucci

**Comment by claudia-lat** [comment]
@Yeshasvitvs the fake links in the new models do not have mass values equal to zero because the code creates fake links with small masses in order to be visualized in Gazebo https://github.com/dic-iit/human-model-generator/blob/master/human_23links/src/createXsensLikeURDFmodel.m#L290

**Comment by yeshasvitirupachuri** [comment]
@claudia-lat yes I understand and that is the reason I want to avoid the regeneration of models. If we regenerate, these new models may cause some other issues down the line in some code which assumed zero mass and inertial values for the links. So, instead we correct  just the `RightHand` link values similar to the `LeftHand` link values of mass and inertia

**Comment by claudia-lat** [comment]
@Yeshasvitvs if you want models with zero mass for the fake links, launch the code with option `false` here https://github.com/dic-iit/human-model-generator/blob/master/human_23links/computeHumanURDF.m#L145

**Comment by yeshasvitirupachuri** [comment]
A PR is open to address this issue https://github.com/robotology/human-gazebo/pull/13

Further I double checked all the models with the test script from #11 

@claudia-lat @lrapetti @DanielePucci
